name: Flutter Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "shots_studio/**"
      - ".github/workflows/flutter_test.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.4"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get
        working-directory: shots_studio

      - name: Run tests
        run: flutter test
        working-directory: shots_studio
